version: '3.9'

services:
  main_program:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: "warn"
    deploy:
      resources:
        limits:
          memory: 512M

  test_program:
    build:
      context: .
      dockerfile: ./perf/Dockerfile
    depends_on:
      - main_program
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

