global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'synapse'
    scrape_interval: 5s
    static_configs:
      - targets: ['synapse:8080']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
